Rework Team Page to fit CLARK and CARD
Cyber4All/CLARK-Team pull request #43
Opened 2021-01-28 17:46 UTC by Cwagne17

Have not finished yet. Just wanted to get input.
[Story 3401](https://app.clubhouse.io/clarkcan/story/3401/rework-clark-team-page-to-fit-for-both-projects)

I added CARD logo to top.
I changed it to SecEd inc.
I also changed background when opening individual members

I tried adding a right side logo for CARD that way it isn't just CLARK for each team member, it did not fit. Any ideas?

I was also going to add a link to CARD and CLARK respectively to the logos at the top.

![Screen Shot 2021-01-28 at 12 43 35 PM](https://user-images.githubusercontent.com/70287489/106177385-7278a600-6166-11eb-870e-614b87ef4fd1.png)
![Screen Shot 2021-01-28 at 12 43 56 PM](https://user-images.githubusercontent.com/70287489/106177425-7efcfe80-6166-11eb-9497-14babe1b13b6.png)

2021-01-28 18:43 UTC, EVogel1999 reviewed
Looks good!  Just some small things.  We should also double-check in case people want to change their bios

2021-01-28 18:43 UTC, EVogel1999 commented on src/app/app.component.html
>          <div class="logos-images" ></div>
Let's delete this if its commented out

2021-01-28 18:43 UTC, EVogel1999 commented on src/app/app.component.html
> +    <!--<a class="small-text" href="https://towson.joinhandshake.com/jobs/4008513?ref=preview-header-click">Are you a Towson student interested in joining the team? Check out our opening for a Softwa
Same here.

2021-01-28 18:43 UTC, EVogel1999 commented on src/app/app.component.html
> +            <div class="right_logo"></div>
What's this supposed to do?

2021-01-28 18:56 UTC, Cwagne17 commented on src/app/app.component.html
> +    <!--<a class="small-text" href="https://towson.joinhandshake.com/jobs/4008513?ref=preview-header-click">Are you a Towson student interested in joining the team? Check out our opening for a Softwa
@EVogel1999 The reason I think keeping this commented piece may be good is incase we were wanting to add back the add for a job in the future. If not I can delete it.

2021-01-28 19:12 UTC, pzalep1 requested changes
Could we also get rid of the clouds in the background? I'm not really sure they fit anymore.

2021-01-28 19:12 UTC, pzalep1 commented on src/app/app.component.html
> +    <!--<a class="small-text" href="https://towson.joinhandshake.com/jobs/4008513?ref=preview-header-click">Are you a Towson student interested in joining the team? Check out our opening for a Softwa
We just remove it since in the future we will be probably be posting this somewhere else.

2021-01-28 19:12 UTC, pzalep1 commented on src/app/app.component.html
> +            <div class="right_logo"></div>
We just remove the logo all together until we get a secureEd logo.

2021-01-28 19:12 UTC, pzalep1 commented on src/app/app.component.html
> +      Meet the <span>SecEd inc.</span> Team
```suggestion
      Meet the <span>SecurEd Inc.</span> Team
```

2021-01-28 20:14 UTC, pzalep1 commented
Thoughts on maybe using the light blue color I sent in the dev chat for the blues on this page? 

The dark blue is old CLARK blue.

2021-02-01 18:55 UTC, Cwagne17 commented
![image](https://user-images.githubusercontent.com/70287489/106504583-234bb180-6495-11eb-82ad-0a97a058b894.png)
![image](https://user-images.githubusercontent.com/70287489/106504604-2b0b5600-6495-11eb-8208-d4338ab74eff.png)

2021-02-01 21:10 UTC, EVogel1999 approved these changes

2021-02-01 21:10 UTC, EVogel1999 commented on src/_vars.scss
> +$clark-blue: #608FF6;
@pzalep1 Just double checking that this is the correct color, or should it be #1c70dd?

2021-02-01 21:10 UTC, EVogel1999 commented
Just for reference, this will need a manual deployment.

2021-02-01 21:12 UTC, pzalep1 commented on src/_vars.scss
> +$clark-blue: #608FF6;
This is a new blue. It's cornflower. We could probably update the name of the variable, but it's not super pressing unless someone has an argument to change it now.

2021-02-01 21:13 UTC, pzalep1 approved these changes
Looks good!

2021-02-01 21:13 UTC, EVogel1999 commented on src/_vars.scss
> +$clark-blue: #608FF6;
I don't have an argument.  I'm going to resolve this comment now.  Thank you for responding!

2021-02-01 21:29 UTC, mfranz1 approved these changes

2021-02-02 15:19 UTC, devky690 approved these changes

2021-02-03 15:45 UTC, merged